"use client"

import * as React from "react"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"
import { Separator } from "@/components/ui/separator"
import { Sparkles } from "lucide-react"

import { SalesAssistantResult } from "@/lib/sales-types"

interface QualificationVerdictProps {
  result: SalesAssistantResult | null
}

export function QualificationVerdict({ result }: QualificationVerdictProps) {
  const getBadgeVariant = (status?: string) => {
    switch (status?.toLowerCase()) {
      case "qualified":
        return "default"
      case "nurture":
        return "secondary"
      case "disqualified":
        return "destructive"
      default:
        return "outline"
    }
  }

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle>Lead Qualification Verdict</CardTitle>
          {result && (
            <Badge variant={getBadgeVariant(result.status)}>
              {result.status.toUpperCase()}
            </Badge>
          )}
        </div>
        <CardDescription>
          BANT evaluation score & decision matrix generated by the scoring node
        </CardDescription>
      </CardHeader>
      <CardContent>
        {result ? (
          <div className="flex flex-col gap-6">
            {/* Score Bar */}
            <div className="flex flex-col gap-2">
              <div className="flex justify-between items-baseline">
                <span className="text-xs text-muted-foreground font-semibold uppercase tracking-wider">
                  BANT Composite Score
                </span>
                <span className="text-2xl font-bold font-mono">
                  {result.score}
                  <span className="text-sm font-normal text-muted-foreground">/100</span>
                </span>
              </div>
              <Progress value={result.score} />
            </div>

            <Separator />

            {/* BANT Metrics Grid */}
            <div className="grid grid-cols-2 gap-4">
              <div className="p-3 rounded-lg border bg-muted/30">
                <div className="text-xs text-muted-foreground font-medium">Budget Verified</div>
                <div className="text-base font-semibold mt-1">
                  ${result.qualification?.budget_amount?.toLocaleString() || "50,000"}
                </div>
                <div className="text-xs text-emerald-600 dark:text-emerald-400 mt-1">
                  ✓ Identified & Allocated
                </div>
              </div>

              <div className="p-3 rounded-lg border bg-muted/30">
                <div className="text-xs text-muted-foreground font-medium">Decision Authority</div>
                <div className="text-base font-semibold mt-1">Executive Sponsor</div>
                <div className="text-xs text-emerald-600 dark:text-emerald-400 mt-1">
                  ✓ VP / Head of Product Verified
                </div>
              </div>

              <div className="p-3 rounded-lg border bg-muted/30">
                <div className="text-xs text-muted-foreground font-medium">Timeline</div>
                <div className="text-base font-semibold mt-1">
                  {result.qualification?.timeline || "Within 2 months"}
                </div>
                <div className="text-xs text-muted-foreground mt-1">Target Procurement Q4</div>
              </div>

              <div className="p-3 rounded-lg border bg-muted/30">
                <div className="text-xs text-muted-foreground font-medium">Workflow Route</div>
                <div className="text-base font-semibold mt-1">
                  {result.status === "qualified"
                    ? "Direct Cold Outreach"
                    : result.status === "nurture"
                    ? "30-Day Drip Campaign"
                    : "CRM Archive"}
                </div>
                <div className="text-xs text-muted-foreground mt-1">Automated Handoff</div>
              </div>
            </div>
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center py-10 text-center text-muted-foreground">
            <Sparkles className="h-8 w-8 mb-2 opacity-40" />
            <div className="text-sm font-medium">No execution result yet</div>
            <div className="text-xs mt-1">Trigger the sales assistant on the left to evaluate a lead.</div>
          </div>
        )}
      </CardContent>
    </Card>
  )
}
