/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "../../packages/ui/src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#0b1326",
        "on-background": "#dae2fd",
        surface: "#0b1326",
        "on-surface": "#dae2fd",
        "surface-dim": "#0b1326",
        "surface-bright": "#31394d",
        "surface-variant": "#2d3449",
        "on-surface-variant": "#c7c4d7",
        "surface-container-lowest": "#060e20",
        "surface-container-low": "#131b2e",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3d",
        "surface-container-highest": "#2d3449",
        "inverse-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        outline: "#908fa0",
        "outline-variant": "#464554",
        primary: {
          DEFAULT: "#c0c1ff",
          fixed: "#e1e0ff",
          "fixed-dim": "#c0c1ff",
          container: "#8083ff",
        },
        "on-primary": "#1000a9",
        "on-primary-container": "#0d0096",
        "on-primary-fixed": "#07006c",
        "on-primary-fixed-variant": "#2f2ebe",
        "inverse-primary": "#494bd6",
        secondary: {
          DEFAULT: "#ddb7ff",
          fixed: "#f0dbff",
          "fixed-dim": "#ddb7ff",
          container: "#6f00be",
        },
        "on-secondary": "#490080",
        "on-secondary-container": "#d6a9ff",
        "on-secondary-fixed": "#2c0051",
        "on-secondary-fixed-variant": "#6900b3",
        tertiary: {
          DEFAULT: "#4edea3",
          fixed: "#6ffbbe",
          "fixed-dim": "#4edea3",
          container: "#00885d",
        },
        "on-tertiary": "#003824",
        "on-tertiary-container": "#000703",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        error: {
          DEFAULT: "#ffb4ab",
          container: "#93000a",
        },
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        card: {
          DEFAULT: "rgba(15, 23, 42, 0.75)",
          foreground: "#dae2fd",
        },
        popover: {
          DEFAULT: "#0b1326",
          foreground: "#dae2fd",
        },
        muted: {
          DEFAULT: "#171f33",
          foreground: "#908fa0",
        },
        accent: {
          DEFAULT: "#222a3d",
          foreground: "#dae2fd",
        },
        border: "rgba(255, 255, 255, 0.1)",
        input: "rgba(255, 255, 255, 0.15)",
        ring: "#c0c1ff",
      },
      spacing: {
        "stack-lg": "32px",
        "margin-mobile": "16px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "margin-desktop": "40px",
        "container-max": "1440px",
        unit: "4px",
        gutter: "24px",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-mono": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

